name: Arm build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install wget curl build-essential libssl-dev libgmp-dev libminiupnpc-dev libboost-all-dev libprotobuf-dev libqrencode-dev g++-arm-linux-gnueabihf -y

      - name: Install BerkelyDB
        run: |
          wget https://github.com/BastelPichi/berkely-db-fixed/releases/download/fix/db-4.8.30.NC.tar.gz
          tar xf db-4.8.30.NC.tar.gz
          cd db-4.8.30.NC/build_unix
          ../dist/configure -q --disable-shared --enable-cxx --disable-replication --with-pic --host=arm-linux-gnueabihf CXX=../dist/configure -q --disable-shared --enable-cxx --disable-replication --with-pic --host=arm-linux-gnueabihf CXX=arm-linux-gnueabihf-g++
          make
          sudo make install

      - name: Compile Magi
        run: |
          cd $HOME/work/magi/magi/src
          export BDB_LIB_PATH=/usr/local/BerkeleyDB.4.8/lib
          export BDB_INCLUDE_PATH=/usr/local/BerkeleyDB.4.8/include
          make -f makefile.unix STATIC=1 HOST=arm-linux-gnueabihf CXX=g++-arm-linux-gnueabihf xCPUARCH=aarch64 STATIC=1
          strip magid
          
      - name: Upload
        uses: actions/upload-artifact@v4.3.3
        with:
          name: magid-dev
          path: /home/runner/work/magi/magi/src/magid
